#!/bin/sh

## autoload vcs and colors
autoload -Uz vcs_info
autoload -U colors && colors

# enable only git 
zstyle ':vcs_info:*' enable git 

# setup a hook that runs before every ptompt. 
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst

# add a function to check for untracked files in the directory.
# from https://github.com/zsh-users/zsh/blob/master/Misc/vcs_info-examples
zstyle ':vcs_info:git*+set-message:*' hooks git-untracked
# 
+vi-git-untracked(){
    if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] && \
        git status --porcelain | grep '??' &> /dev/null ; then
        # This will show the marker if there are any untracked files in repo.
        # If instead you want to show the marker only if there are untracked
        # files in $PWD, use:
        #[[ -n $(git ls-files --others --exclude-standard) ]] ; then
        hook_com[staged]+='!' # signify new files with a bang
    fi
}

# Gruvbox Colors
# bred='#fb4934'
# bgreen='#b8bb26'
# borange='#fe8019'
# byellow='#fabd2f'
# bblue='#83a598'
# baqua='#8ec07c'
# bpurple='#d3869b'
# ggray='#928374'
# flight='#fbf1c7'

# NightFox Colors
# bred="#c94f6d",
# bgreen="#81b29a",
# byellow="#dbc074",
# bblue="#7daea3",
# baqua="#63cdcf",
# borange="#f4a261",
# bpurple="#d67ad2",
# black="#393b44",
# flight="#dfdfe0",

# Rose-Pine
bred='#eb6f92',
bgreen="#81b29a",
byellow='#f6c177',
bblue='#31748f',
baqua='#9ccfd8',
borange='#ebbcba',
bpurple='#c4a7e7',
black='#21202e',
flight='#e0def4',

zstyle ':vcs_info:*' check-for-changes true
# zstyle ':vcs_info:git:*' formats " %r/%S %b %m%u%c "
zstyle ':vcs_info:git:*' formats " %F{$flight}(%F{$bred}%m%u%c%F{$byellow}%F{$bpurple} %b%F{$flight})"

# format our main prompt for hostname current folder, and permissions.
PS1="%F{$flight}[%F{$baqua}%n%F{$flight}] %(?:%F{$bgreen}➜ :%F{$bred}➜ )%F{$bblue}%c%F{$reset_color}"

# PS1="%{$fg[blue]%}[%{$fg[white]%}%n%{$fg[red]%}@%{$fg[white]%}%m%{$fg[blue]%}] %(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )%{$fg[cyan]%}%c%{$reset_color%}"
# PROMPT="%{$fg[green]%}%n@%m %~ %{$reset_color%}%#> "
PS1+="\$vcs_info_msg_0_"
PS1+="%F{$flight} "
