#!/bin/sh
# HISTFILE="$XDG_DATA_HOME"/zsh/history
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH

export PATH="$HOME/tools/stylua0.11.2":$PATH
export PATH="$HOME/tools/lua-language-server/bin":$PATH

# Python Env Storage
source "$HOME/.local/bin/virtualenvwrapper.sh"
export PY_ENV="$HOME/.virtualenvs/envs"
export VIRTUALENVWRAPPER_PYTHON="/usr/bin/python3"

export PATH="$HOME/tools/sqlite3/sqlite-tools-linux-x86-3380500":$PATH

export DENO_INSTALL="/home/dkeith/.deno"
export PATH="$DENO_INSTALL/bin:$PATH"

export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH="$HOME/tools/llvm-project/build/bin:$PATH"
export LD_LIBRARY_PATH="$HOME/tools/llvm-project/build/lib:$LD_LIBRARY_PATH"
export DOTFILES="$HOME/.dotfiles"

# export CC="clang"
# export CFLAGS="-ggdb3 -O0 -std=c11 -Wall -Werror -Wextra -Wno-sign-compare -Wno-unused-parameter -Wno-unused-variable -Wshadow"
# export LDLIBS="-lcrypt -lcs50 -lm"

. "$HOME/.cargo/env"

export NVM_DIR="$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.nvm" || printf %s "${XDG_CONFIG_HOME}/nvm")"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh" # This loads nvm

export PATH="$PATH:$HOME/bin"
