#!/bin/sh

## autoload vcs and colors
autoload -Uz vcs_info
autoload -U colors && colors

# enable only git
zstyle ':vcs_info:*' enable git

# setup a hook that runs before every ptompt.
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )
setopt prompt_subst

# add a function to check for untracked files in the directory.
# from https://github.com/zsh-users/zsh/blob/master/Misc/vcs_info-examples
zstyle ':vcs_info:git*+set-message:*' hooks git-untracked
#
+vi-git-untracked(){
    if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] && \
        git status --porcelain | grep '??' &> /dev/null ; then
        # This will show the marker if there are any untracked files in repo.
        # If instead you want to show the marker only if there are untracked
        # files in $PWD, use:
        #[[ -n $(git ls-files --others --exclude-standard) ]] ; then
        hook_com[staged]+='!' # signify new files with a bang
    fi
}

# Gruvbox Colors
# red='#fb4934'
# green='#b8bb26'
# orange='#fe8019'
# yellow='#fabd2f'
# blue='#83a598'
# aqua='#8ec07c'
# purple='#d3869b'
# ggray='#928374'
# light='#ff1c7'

# NightFox Colors
# red="#c94f6d",
# green="#81b29a",
# yellow="#dbc074",
# blue="#7daea3",
# aqua="#63cdcf",
# orange="#f4a261",
# purple="#d67ad2",
# black="#393b44",
# light="#dfdfe0",

# Rose-Pine
# red="#eb6f92",
# green="#9ccfd8",
# yellow="#f6c177",
# blue="#31748f",
# purple="#c4a7e7",
# cyan="#ebbcba",
# light="#e0def4",
# black="#6e6a86",

# Tokyonight
black='#1D202F',
red='#f7768e',
green='#9ece6a',
yellow='#e0af68',
blue='#7aa2f7',
purple='#bb9af7',
cyan='#7dcfff',
light='#a9b1d6',

zstyle ':vcs_info:*' check-for-changes true
# zstyle ':vcs_info:git:*' formats " %r/%S %b %m%u%c "
zstyle ':vcs_info:git:*' formats "%F{$light}(%F{$red}%m%u%c%F{$yellow}%F{$purple} %b%F{$light})"

# format our main prompt for hostname current folder, and permissions.
PS1="%F{$cyan}[%F{$red}%n%F{$cyan}] %(?:%F{$green}➜ :%F{$red}➜ )%F{$cyan}%c%F{$reset_color}"

# PS1="%{$fg[blue]%}[%{$fg[white]%}%n%{$fg[red]%}@%{$fg[white]%}%m%{$fg[blue]%}] %(?:%{$fg_bold[green]%}➜ :%{$fg_bold[red]%}➜ )%{$fg[cyan]%}%c%{$reset_color%}"
# PROMPT="%{$fg[green]%}%n@%m %~ %{$reset_color%}%#> "
PS1+="\$vcs_info_msg_0_"
PS1+="%F{$light} "
